###get 

GET http://localhost:3000/api/boardgames



### post

POST http://localhost:3000/api/boardgames
Content-Type: application/json

{
    "name": "Uno",
    "minAge": 8,
    "minPlayers": 3,
    "maxPlayers": 6,
    "type": "déduction",
    "note": 4,
    "duration": 20,
    "creator": "Anthony Pratt"
}